#pragma once
#include "framework.h"
void OlympicEmblem(HDC hdc);
void oblaka(HDC  hdc);
void budiln(HDC hdc);
void Cor(HDC hdc, int cx, int cy, int sizeX, int sizeY, COLORREF color);
void cor_gor(HDC hdc);
void cor_ver(HDC hdc);
void cor_riad(HDC hdc);
void cor_diag(HDC hdc);
void MyFigure(HDC hdc, int cx, int cy, int sizeX, int sizeY, COLORREF color);
void f_gor(HDC hdc);
void f_riad(HDC hdc);
void f_diag(HDC hdc);
void f_ver(HDC hdc);
void f_p(HDC hdc);
void Claus(HDC hdc, int x, int y);
void el(HDC hdc);
void was(HDC hdc);
void centr(HDC hdc);
void line(HDC hdc);
void linever(HDC hdc);
void diag(HDC hdc);
void riad(HDC hdc);
void Sneg(HDC hdc, int x, int y);
void Logo(HDC hdc, int x, int y);
void centr_logo(HDC hdc);
void line_logo(HDC hdc);
void linever_Logo(HDC hdc);
void diag_Logo(HDC hdc);
void riad_Logo(HDC hdc);
void im1(HDC hdc, int cx, int cy, int size);
void recurklim1_1(HDC hdc, int cx, int cy, int size);
void recurklim1_2(HDC hdc, int cx, int cy, int size);
void recurklim1_3(HDC hdc, int cx, int cy, int size);
void recurklim1_4(HDC hdc, int cx, int cy, int size);
void recurklim1_5(HDC hdc, int cx, int cy, int size);
void recurklim1_6(HDC hdc, int cx, int cy, int size);
void recurklim1_7(HDC hdc, int cx, int cy, int size);
void recurklim1_8(HDC hdc, int cx, int cy, int size);
void im2(HDC hdc, int cx, int cy, int size);
void recurklim2_1(HDC hdc, int cx, int cy, int size);
void recurklim2_2(HDC hdc, int cx, int cy, int size);
void recurklim2_3(HDC hdc, int cx, int cy, int size);
void recurklim2_4(HDC hdc, int cx, int cy, int size);
void recurklim2_5(HDC hdc, int cx, int cy, int size);
void im3(HDC hdc, int cx, int cy, int size);
void recurs_troi(HDC hdc, int cx, int cy, int size);
void recurs_troi2(HDC hdc, int cx, int cy, int size);
void recurs_troi3(HDC hdc, int cx, int cy, int size);
void im4(HDC hdc, int cx, int cy, int size);
void im5(HDC hdc, int cx, int cy, int size);
void recurs_kvadr(HDC hdc, int cx, int cy, int size);
void recurs_kvadr2(HDC hdc, int cx, int cy, int size);
void im6(HDC hdc, int cx, int cy, int size);
void recurs_krug(HDC hdc, int cx, int cy, int size);
void recurs_krug2(HDC hdc, int cx, int cy, int size);
void recurs_krug3(HDC hdc, int cx, int cy, int size);
void im7(HDC hdc, int cx, int cy, int size);
void first_house(HDC hdc);
void Big_PIC(HDC hdc);
